name: Generate PR Report

on:
  pull_request:
    types: [opened, reopened, closed, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR details
        id: pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR report (Markdown)
        shell: bash
        run: |
          cat << 'EOF' > pr-report.md
          # Pull Request Report

          - **Title:** ${{ fromJson(steps.pr.outputs.data).title }}
          - **Author:** ${{ fromJson(steps.pr.outputs.data).user.login }}
          - **State:** ${{ fromJson(steps.pr.outputs.data).state }}
          - **Commits:** ${{ fromJson(steps.pr.outputs.data).commits }}
          - **Files Changed:** ${{ fromJson(steps.pr.outputs.data).changed_files }}
          - **Created At:** ${{ fromJson(steps.pr.outputs.data).created_at }}
          - **URL:** ${{ fromJson(steps.pr.outputs.data).html_url }}

          ---

          ## Description

          ${{ fromJson(steps.pr.outputs.data).body || 'No description provided.' }}
          EOF

      - name: Convert Markdown to HTML and PDF
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf
          pandoc -s pr-report.md -o pr-report.html
          wkhtmltopdf pr-report.html pr-report.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-report
          path: |
            pr-report.md
            pr-report.pdf
